[package]
name = "ai-gateway-client"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web & Async
async-trait = { workspace = true }
reqwest = { workspace = true }

# Serialization
serde ={ workspace = true }
serde_json = { workspace = true }

# OpenAPI
utoipa = { workspace = true, optional = true }

# Utils
thiserror = { workspace = true }

[features]
default = []
openapi = ["dep:utoipa"]