name: hse-ai-ecosystem-interface

networks:
  hse_ai_ecosystem:
    external: true
  infra_monitoring_net:
    external: true

services:
  tg-controller:
    build:
      context: ./tg-controller
      dockerfile: Dockerfile
    container_name: hse-tg-controller
    restart: always
    ports:
      - "8092:8000"
    env_file: ./tg-controller/.env
    environment:
      - WEB_CONCURRENCY=1
    depends_on:
      - ai-router
    networks:
      - hse_ai_ecosystem
      - infra_monitoring_net

  alice-controller:
    build:
      context: ./alice-controller
      dockerfile: Dockerfile
    container_name: hse-alice-controller
    restart: always
    ports:
      - "8093:8000"
    environment:
      - WEB_CONCURRENCY=2
    env_file: ./alice-controller/.env
    depends_on:
      - ai-router
    networks:
      - hse_ai_ecosystem
      - infra_monitoring_net

  vk-controller:
    build:
      context: ./vk-controller
      dockerfile: Dockerfile
    container_name: hse-vk-controller
    restart: always
    ports:
      - "8094:8000"
    env_file: ./vk-controller/.env
    environment:
      - WEB_CONCURRENCY=1
    depends_on:
      - ai-router
    networks:
      - hse_ai_ecosystem
      - infra_monitoring_net