name: hse-ai-ecosystem-storage

networks:
  hse_ai_ecosystem:
    driver: bridge
    name: hse_ai_ecosystem

services:
  postgres:
    image: postgres:14.5
    container_name: hse-postgres
    restart: always
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
      - ./init/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hse_ai_ecosystem

  redis:
    image: redis:alpine
    container_name: hse-redis
    restart: always
    volumes:
      - ./storage/redis_data:/data
    networks:
      - hse_ai_ecosystem

  qdrant:
    image: qdrant/qdrant:latest
    container_name: hse-qdrant
    restart: always
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    volumes:
      - ./storage/qdrant_data:/qdrant/storage
    networks:
      - hse_ai_ecosystem

  dufs:
    image: sigoden/dufs:latest
    container_name: dufs_storage
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./storage/dufs:/data
    deploy:
      resources:
        limits:
          memory: 64M
    command: >
      /data
      -a "admin:${DUFS_API_KEY}@/:rw"
      -a "@/:ro"
      -A
      --render-index
      --auth-method basic