[package]
name = "hse-ai-gateway"
version = "1.0.0"
edition = "2024"

[dependencies]
# Web & Async
axum = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

# Serialization
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

# Metrics & Logging
metrics = { workspace = true }
tracing = { workspace = true }

# OpenAPI
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }


# Internal
ai-gateway-client = { workspace = true }
common-infra = { workspace = true }