[package]
name = "hse-moodle-extractor"
version = "1.0.0"
edition = "2024"

[dependencies]
# Web & Async
axum = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
tokio = { workspace = true }

# Serialization
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Metrics & Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }