{
 "title": "AI Gateway: LLM & Providers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Provider Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ai_provider_status", "legendFormat": "{{provider_id}}" }
   ]
  },
  {
   "title": "Models Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "ai_model_status" }
   ]
  },
  {
   "title": "Average Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (provider, model) (rate(ai_request_duration_seconds_sum[$__rate_interval])) \r\n/ \r\nsum by (provider, model) (rate(ai_request_duration_seconds_count[$__rate_interval]))* 1000",
     "legendFormat": "{{provider}} / {{model}}"
    }
   ]
  },
  {
   "title": "Tokens Spent (Rate / Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (mode) (rate(ai_tokens_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total tokens per mode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode) (increase(ai_tokens_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Requests (by Status Code)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (model, status_code) (rate(ai_requests_total{status_code!=\"error\"}[$__rate_interval]))",
     "legendFormat": "{{model}} - HTTP {{status_code}}"
    }
   ]
  }
 ]
}