[package]
name = "kb-common"
version = "1.0.0"
edition = "2024"

[dependencies]
sea-query = { workspace = true }
sea-query-binder = { workspace = true }
sqlx = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }