[package]
name = "hse-kb-controller"
version = "1.0.0"
edition = "2024"

[dependencies]
# Web & Async
axum = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

# Serialization
bincode = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Database
sqlx = { workspace = true }

# Hashing
hex = { workspace = true }
sha2 = { workspace = true }

# Metrics & Logging
tracing = { workspace = true }

# OpenAPI
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

# Utils
uuid = { workspace = true }

# Internal
ai-gateway-client = { workspace = true }
doc-processor-client = { workspace = true }
common-infra = { workspace = true }
kb-common = { workspace = true }