[package]
name = "hse-kb-interface"
version = "1.0.0"
edition = "2021"

[dependencies]
# Web & Async
tokio = { version = "1.35", features = ["full"] }
axum = { version = "0.7.9", features = ["multipart", "macros"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "rustls-tls"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
dotenvy = "0.15"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "chrono", "macros"] }

# Hashing
sha2 = "0.10"
hex = "0.4"

# Metrics & Logging
prometheus = { version = "0.13", default-features = true, features = ["process"]}
lazy_static = "1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Swagger / OpenAPI
utoipa = { version = "4.2", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "6.0", features = ["axum"] }

# Utils
uuid = { version = "1.7", features = ["v4"] }
futures = "0.3.32"
config = "0.15.22"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"