[package]
name = "hse-kb-interface"
version = "1.0.0"
edition = "2024"

[dependencies]
# Web & Async
axum = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

# Serialization
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Database
sqlx = { workspace = true }

# Metrics & Logging
tracing = { workspace = true }

# Swagger / OpenAPI
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

# Internal
ai-gateway-client = { workspace = true }
common-infra = { workspace = true }
kb-common = { workspace = true }